[build]
target_dir = "dist"

[serve]
port = 8080
open = true

[watch]
features = []

[tools.tailwind]
config = "tailwind.config.js"
css_file = "dist/style.css"
input = "public/style.css"
output = "dist/style.css"
